import "./globals.css";
import inter_init from "./fonts";

export const metadata = {
  title:
    "disney+ Hotstar - Watch TV Shows, Movies, Specials, Live Cricket & Football",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter_init}`}>{children}</body>
    </html>
  );
}
